# Generated by Django 5.2.1 on 2025-06-04 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculums",
                to="lms.student",
            ),
        ),
        migrations.AddField(
            model_name="curriculum",
            name="target_mastery",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="class_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="contact",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="lms.student"
            ),
        ),
    ]
